Initialise project components
Zibilyonik/redux-bookstore pull request #1
Opened 2021-08-24 14:36 UTC by Zibilyonik

Create a basic create react app with some working directory set up for the next milestone.
Set up linters.
Set Route and Switch for Bookstore component.

2021-08-24 14:45 UTC, mikenath223 requested changes
Hello @Zibilyonik 👋,

You've done pretty well so far!
But for a few issues, you are almost done with this. Hang in there!


## Required Changes ♻️
_Please check the comments under the review._

Happy coding, Cheers! 🚀🚀

Do feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it is valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-24 14:46 UTC, mikenath223 commented on README.md
> +### `yarn start`
- [ ] Kindly update the readme and ensure it follows [this template](https://github.com/microverseinc/readme-template).

2021-08-24 14:47 UTC, mikenath223 commented on src/components/Bookstore.js
> +  </Switch>
- [ ] Kindly move these routes to the top level container `App.js`.

2021-08-24 14:48 UTC, mikenath223 commented on src/components/Bookstore.js
> +      <h1>Under Construction</h1>
- [ ] In App.js, the categories route should display the Categories component. So kindly create a Categories component and in it return the `Under construction` text.

2021-08-24 14:49 UTC, mikenath223 commented on src/App.js
> +  return (
- [ ] Please create a BookList component that renders a list of Books using the Book component.

2021-08-24 14:50 UTC, mikenath223 commented on src/App.js
> +  );
- [ ] Also, create a Book component that takes the book data as a prop and renders the title and the author.

2021-08-24 14:51 UTC, mikenath223 commented on src/App.js
> +  );
- [ ] The Book component should also have a button for removing books, the button wouldn't remove the books yet, this is just a placeholder for now.

2021-08-24 14:53 UTC, mikenath223 commented on src/App.js
> +
- [ ] Also add a CreateNewBook component it should render a form with inputs for the title and the author of the book, it should also have a button to submit, it won't actually submit but it's just a placeholder for now.

2021-08-24 14:55 UTC, mikenath223 commented on src/components/Bookstore.js
> +  </Switch>
- [ ] Also there should be two `<Link>`s in the navbar on the App.js container which leads to the booklist and categories locations. You can put the NavBar as a component.

2021-08-25 13:44 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-08-25 14:04 UTC, merged